config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  
  get 'books/all' => 'books#all', as: 'all_books'
  get 'search' => 'books#search'
  get 'admin' => 'sessions#new', as: 'admin'
  get 'return' => 'users#return', as: 'return_book'

  get 'books/manage' => 'books#manage', as: 'manage_books'
  get 'books/list' => 'books#list', as: 'list_books'
  get 'orders/manage' => 'orders#manage', as: 'manage_orders'
  get 'orders/history' => 'orders#history', as: 'order_history'
  get 'rentals/manage' => 'rentals#manage', as: 'manage_rentals'
  get 'rentals/history' => 'rentals#history', as: 'rental_history'
  put 'orders/manage/:id/moderate' => 'orders#moderate', as: 'moderate_order'
  put 'orders/manage/:id/complete' => 'orders#complete', as: 'complete_order'

  resources :books do
    resources :rentals
  end

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :orders
  resources :categories

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rentals, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  has_secure_password

  # validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :department, presence: true

  validates :email,
    format: { with: /\S+@\S+/ },
    uniqueness: { case_sensitive: false }

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def first_name_and_initials
    "#{first_name.capitalize} #{last_name[0].capitalize}."
  end

  def unreturned_rentals
    rentals.where(returned: false)
  end

  def returned_rentals
    rentals.where(returned: true)
  end

  def admin?
    admin && role == 'admin'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, only: [:index, :create]
  before_action :require_admin, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    @user.password = "0000"
    @user.password_confirmation = "0000"

    if @user.save
      redirect_to manage_books_path, notice: 'Пользователь был успешно добавлен!'
    else
      render :new
    end
  end

  def show
    email = get_email_from_param(params[:account])
    @user = User.find_by email: email
    
    if @user.nil?
      redirect_to return_book_url, alert: 'Неправильный ID (или почта)'
    end
  end

  def return
  end

  private

  def get_email_from_param(string)
    return string if string.include?('@')

    "#{string}@evrika.com"
  end

  def user_params
    params.require(:user)
      .permit(:first_name, :last_name, :email, :department)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: 'flex flex-col') do |f| %>

  <%= render 'shared/errors', object: user %>

  <div class="mb-4">
    <%= f.label :first_name, 'Имя', class: 'text-gray-600' %><br>
    <%= f.text_field :first_name,
                      autofocus: true, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :last_name, 'Фамилия', class: 'text-gray-600' %><br>
    <%= f.text_field :last_name,
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :email, 'Корпоративная почта', class: 'text-gray-600' %><br>
    <%= f.email_field :email,
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :department, 'Отдел', class: 'text-gray-600' %><br>
    <%= f.text_field :department,
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.submit 'Добавить',
                  class: 'cursor-pointer text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6' %>
  </div>

<% end %>

app/views/users/index.html.erb
<div class="text-2xl font-bold pb-2">Список пользователей</div>

<ul class="py-3 list-inside list-disc">
  <% @users.each do |user| %>
    <% if user.role == 'admin' %>
      <li class="font-bold text-purple-500">
        <%= user.first_name %> <%= user.last_name %>
        <%= mail_to user.email, "<#{user.email}>" %>
      </li>
    <% else %>
      <li>
        <%= user.first_name %> <%= user.last_name %>
        <%= mail_to user.email, "<#{user.email}>" %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="text-2xl font-bold pb-2">
  Добавить нового пользователя
</div>

<section class="flex p-6 my-4 bg-green-50">
  <%= render 'form', user: @user %>
</section>

app/views/users/return.html.erb
<div class="text-2xl font-bold pb-2">Вернуть прочитанную книгу</div>

<p class="my-3"><strong>Напоминание:</strong> Вы собираетесь вернуть книгу на полку. Наша библиотека доверяет Вам, поэтому мы не просим логин/пароль. Просто введите ваш корпоративный ID и всё ☺️</p>

<form action="/users/show" method="get" class="<%= tw(:return_form) %>">
  <div class="mb-4">
    <label for="account" class="text-gray-600">Корпоративный ID (или почта)</label><br>
    <input type="text" name="account" id="account" class="<%= tw(:form_input) %>">
  </div>

  <div class="mb-4">
    <input type="submit" value="Посмотреть мои книги 📗" class="cursor-pointer text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6">
  </div>
</form>

app/views/users/show.html.erb
<div class="text-2xl font-bold pb-2">
  Привет, <%= @user.first_name %>! 😉
</div>

<% unless @user.unreturned_rentals.present? %>
  <p>У тебя пока нет никаких книг :)</p>
  <p>Посмотри список книг нашей 
    <%= link_to 'библиотеки', all_books_path, class: tw(:rental_list_book_title) %>
  </p>
<% end %>

<ul>
  <% @user.unreturned_rentals.each do |r| %>
    <li class="list-inside list-decimal mb-3">
      <%= link_to r.book.name, book_path(r.book), class: tw(:rental_list_book_title) %>

      <%= link_to 'Вернуть на полку', book_rental_path(r.book, city: r.got_from, rental_id: r.id),
                  class: tw(:return_book_btn),
                  method: :delete,
                  data: { confirm: 'Вы уверены, что хотите вернуть книгу на полку? Просим не возвращать книгу за чужих пользователей.' } %>
    </li>
  <% end %>
</ul>