config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  
  get 'books/all' => 'books#all', as: 'all_books'
  get 'search' => 'books#search'
  get 'admin' => 'sessions#new', as: 'admin'
  get 'return' => 'users#return', as: 'return_book'

  get 'books/manage' => 'books#manage', as: 'manage_books'
  get 'books/list' => 'books#list', as: 'list_books'
  get 'orders/manage' => 'orders#manage', as: 'manage_orders'
  get 'orders/history' => 'orders#history', as: 'order_history'
  get 'rentals/manage' => 'rentals#manage', as: 'manage_rentals'
  get 'rentals/history' => 'rentals#history', as: 'rental_history'
  put 'orders/manage/:id/moderate' => 'orders#moderate', as: 'moderate_order'
  put 'orders/manage/:id/complete' => 'orders#complete', as: 'complete_order'

  resources :books do
    resources :rentals
  end

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :orders
  resources :categories

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  # validations
  validates :name,
    presence: true,
    length: { maximum: 250 }
  
  validates :author,
    length: {
      minimum: 5,
      maximum: 200
    }

  def self.to_be_ordered
    where(ordered: false, moderated: true)
      .order(created_at: :desc)
  end

  def self.newest
    where(ordered: false)
      .order(created_at: :desc)
  end

  def self.completed
    where(ordered: true)
      .order(created_at: :desc)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :require_signin, only: [:manage, :moderate, :complete, :history]
  before_action :require_admin, only: [:manage, :moderate, :complete, :history]

  def manage
    @orders = Order.newest
  end

  def moderate
    @order = Order.find(params[:id])
    
    # if @order.moderated?
    #   @order.moderated = false
    # else
    #   @order.moderated = true
    # end

    @order.moderated = @order.moderated? ? false : true
    @order.save

    redirect_to manage_orders_url,
      notice: 'Статус модерация заказа успешно обновлён!'
  end

  def complete
    @order = Order.find(params[:id])
    
    @order.ordered = true
    @order.save

    redirect_to new_book_url(
      book_name: @order.name,
      book_author: @order.author
    )
  end

  def history
    @orders = Order.completed
  end

  def index
    @orders = Order.to_be_ordered
  end

  def new
    account = get_email_from_param(params[:account])
    @user = User.find_by email: account

    if @user.nil?
      redirect_to orders_url, alert: 'Неправильный ID (или почта)'
    end

    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    
    if @order.save
      redirect_to orders_url, notice: 'Твой заказ в обработке. Как только он пройдёт модерацию, ты увидишь его в списке желаемой литературы :)'
    else
      render :new
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.delete

    redirect_to manage_orders_url,
      notice: 'Заказ был успешно удалён из базы!'
  end

  private

  def get_email_from_param(string)
    return string if string.include?('@')

    "#{string}@evrika.com"
  end

  def order_params
    params.require(:order)
      .permit(:name, :author, :link, :user_id)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper

  def moderate_link(order)
    flag = order.moderated? ? '🟢' : '🔴'
    
    link_to flag,
      moderate_order_path(order),
      method: :put,
      class: 'mx-1',
      data: {
        confirm: 'Вы уверены, что хотите изменить модерацию этого заказа?'
      }
  end

  def order_done_link(order)
    link_to '☑️',
      complete_order_path(order),
      method: :put,
      class: 'mx-1',
      data: {
        confirm: 'Вы уверены, что хотите изменить статус заказа на "выпонено"?'
      }
  end

  def delete_order_link(order)
    link_to '❌',
      order_path(order),
      method: :delete,
      class: 'mx-1',
      data: {
        confirm: 'Вы уверены, что хотите полностью удалить данный заказ из быза?'
      }
  end

end

app/views/orders/history.html.erb
<div class="text-2xl font-bold pb-2">
  История заказов
</div>

<table class="flex flex-row orders-table">
  
  <tr>
    <th class="bg-blue-100 border text-left px-4 py-2">Название книги</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">От кого</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Создан</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Выполнен</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Действия</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="border px-4 py-2 text-sm">
        <%= order.name %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= order.user.first_name_and_initials %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= order.created_at.strftime('%d.%m.%Yг.') %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= order.updated_at.strftime('%d.%m.%Yг.') %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= delete_order_link(order) %>
      </td>
    </tr>
  <% end %>

</table>

app/views/orders/index.html.erb
<div class="text-2xl font-bold">
  Заказать новую книгу
</div>

<form action="/orders/new" method="get" class="mb-2 <%= tw(:return_form) %>">
  <div class="mb-4">
    <label for="account" class="text-gray-600">Корпоративный ID (или почта)</label><br>
    <input type="text" name="account" id="account" class="<%= tw(:form_input) %>">
  </div>

  <div class="mb-4">
    <input type="submit" value="Заказать новую книгу 📗" class="cursor-pointer text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6">
  </div>
</form>

<% unless @orders.blank? %>
  <div class="text-2xl font-bold pb-2">
    Список желаемой литературы 🐱
  </div>
<% end %>

<ul class="orders flex flex-col">
  <% @orders.each do |order| %>
    <li class="border-2 border-dashed my-3 py-3 px-4">
      <strong>📗 <%= order.name %></strong><br>

      <span class="text-gray-500">✍️ <%= order.author %></span>

      <p class="mt-3">Заказ от 
        <strong class="font-bold text-purple-500">
          <%= order.user.first_name_and_initials %>
        </strong>
      </p>
    </li>
  <% end %>
</ul>

app/views/orders/manage.html.erb
<div class="text-2xl font-bold pb-2">
  Управление заказами
</div>

<p>
  <%= link_to 'История заказов', order_history_path, class: 'text-blue-500 hover:underline' %>
</p>

<% unless @orders.blank? %>
  <table class="flex flex-row orders-table">
    
    <tr>
      <th class="bg-blue-100 border text-left px-4 py-2">Название</th>
      <th class="bg-blue-100 border text-left px-4 py-2 text-center" style="min-width:135px;">От кого</th>
      <th class="bg-blue-100 border text-left px-4 py-2 text-center" style="min-width:120px;">Действия</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td class="border px-4 py-2 text-sm">
          <%= order.name %>
          <span class="block mt-2 italic">
            ✍️ <%= order.author %>
          </span>
        </td>

        <td class="border px-4 py-2 text-sm text-center">
          <%= order.user.first_name_and_initials %>
          <span class="block mt-2 italic">
            <%= order.created_at.strftime('%d.%m.%Yг.') %>
          </span>
        </td>

        <td class="border px-4 py-2 text-sm text-center">
          <%= moderate_link(order) %>
          <%= order_done_link(order) %>
          <%= delete_order_link(order) %>
        </td>
      </tr>
    <% end %>

  </table>
<% end %>

app/views/orders/new.html.erb
<div class="text-2xl font-bold pb-2">
  Заказать новую книгу
</div>

<p class="my-3"><strong>Напоминание:</strong> Привет, <span class="font-bold text-purple-500"><%= @user.first_name %></span>! Ты собираешься заказать новую книгу в нашу скромную библиотеку. Прежде чем заполнить данные желанной книги, ознакомься, пожалуйста, со списком уже заказанных книг <%= link_to 'на странице заказов', orders_path, class: 'font-bold text-blue-500 hover:underline' %> ☺️</p>

<%= form_with(model: @order, local: true, class: 'flex flex-col') do |f| %>

  <%= render 'shared/errors', object: @order %>

  <div class="mb-4">
    <%= f.label :name, 'Название книги', class: 'text-gray-600' %><br>
    <%= f.text_field :name,
                      autofocus: true, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :author, 'Автор', class: 'text-gray-600' %><br>
    <%= f.text_field :author, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :link, 'Ссылка на книгу (не обязательно)', class: 'text-gray-600' %><br>
    <%= f.text_field :link, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <%# FIELD FOR USER %>
  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="mb-4">
    <%= f.submit 'Отправить заявку 🚀',
                  class: 'cursor-pointer text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6' %>
  </div>

<% end %>