config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  
  get 'books/all' => 'books#all', as: 'all_books'
  get 'search' => 'books#search'
  get 'admin' => 'sessions#new', as: 'admin'
  get 'return' => 'users#return', as: 'return_book'

  get 'books/manage' => 'books#manage', as: 'manage_books'
  get 'books/list' => 'books#list', as: 'list_books'
  get 'orders/manage' => 'orders#manage', as: 'manage_orders'
  get 'orders/history' => 'orders#history', as: 'order_history'
  get 'rentals/manage' => 'rentals#manage', as: 'manage_rentals'
  get 'rentals/history' => 'rentals#history', as: 'rental_history'
  put 'orders/manage/:id/moderate' => 'orders#moderate', as: 'moderate_order'
  put 'orders/manage/:id/complete' => 'orders#complete', as: 'complete_order'

  resources :books do
    resources :rentals
  end

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :orders
  resources :categories

end

app/models/book.rb
class Book < ApplicationRecord
  has_many :rentals, dependent: :destroy
  has_many :book_quantities, dependent: :destroy
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  # validations
  validates :name,
    presence: true,
    length: { maximum: 250 }
  
  validates :author,
    length: {
      minimum: 5,
      maximum: 200
    }
  
  validates :description,
    length: { minimum: 100 }
  
  validates :image_src, 
    presence: true, 
    length: { maximum: 250 },
    format: {
      with: /\w+\.(jpg|png|jpeg)\z/i,
      message: 'must be a JPG, JPEG, or PNG'
    }
  
  validates :cit_quantity, :ala_quantity,
    numericality: {
      greater_than_or_equal_to: 0,
      only_integer: true,
    }

  # class methods
  def self.newest
    where(visible: true)
      .order(created_at: :desc)
      .limit(20)
  end
  
  def self.search(query)
    q = '%' + query + '%'
    where('name LIKE ?', q)
  end

  def self.all_ordered_by_name
    order('name ASC')
  end

  def self.all_ordered_by_category(category_id)
    if Category.exists?(category_id) 
      Category.find(category_id).books
    else
      all_ordered_by_name
    end
  end

  def self.all_ordered_by_times_read
    order(times_read: :desc)
  end

  # instance methods
  def rented_out?
    cit_quantity.zero? && ala_quantity.zero?
  end

  def has_readers?
    unreturned_rentals.size > 0
  end

  def available?
    available_in_ala? || available_in_cit?
  end

  def available_in_cit?
    cit_quantity > 0
  end

  def available_in_ala?
    ala_quantity > 0
  end

  def unreturned_rentals
    rentals.where(returned: false)
  end

  def returned_rentals
    rentals.where(returned: true)
  end

  def q_cit_quantity
    book_quantities.first.cit
  end

  def q_ala_quantity
    book_quantities.first.ala
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :require_signin, except: [:index, :show, :all, :search]
  before_action :require_admin, except: [:index, :show, :all, :search, :manage]

  def all
    @categories = Category.all
    
    if params['category_id']
      @books = Book.all_ordered_by_category(params['category_id'])
    else
      @books = Book.all_ordered_by_name
    end
  end

  def search
    @query = params[:query]
    @books = Book.search(params[:query])
  end

  def manage
  end

  def list
    @books = Book.all_ordered_by_times_read
  end

  def index
    @books = Book.newest
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new

    if params[:book_name] && params[:book_author]
      @book.name = params[:book_name]
      @book.author = params[:book_author]
    end
  end

  def create
    @book = Book.new(book_params)

    # add quantities
    q = @book.book_quantities.new
    q.cit, q.ala = @book.cit_quantity, @book.ala_quantity
    
    if @book.save && q.save
      redirect_to book_path(@book), notice: 'Книга была успешна добавлена!'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    # update quantities
    q = @book.book_quantities.first
    q.cit, q.ala = book_params[:cit_quantity], book_params[:ala_quantity]
    
    if @book.update(book_params) && q.save
      redirect_to book_path(@book), notice: 'Книга была успешна обновлена!'
    else
      render :edit
    end
  end

  # toggle effect
  def destroy
    @book = Book.find(params[:id])

    if @book.visible?
      @book.visible = false
      flash[:notice] = 'Успех. Пользователи теперь не увидят эту книгу.'
    else
      @book.visible = true
      flash[:notice] = 'Успех. Пользователи теперь могут увидеть эту книгу.'
    end

    # @book.visible = @book.visible? ? false : true
    @book.save

    if params[:src] && params[:src] == 'dashboard'
      redirect_to list_books_path
    else
      redirect_to book_path(@book)
    end

  end

  private

  def book_params
    params.require(:book)
      .permit(:name, :author, :description, :ala_quantity, :cit_quantity, :image_src, :visible, category_ids: [])
  end

end

app/helpers/books_helper.rb
module BooksHelper

  def cover(book)
    image_tag book.image_src, 
      alt: "Обложка книги #{book.name}",
      class: 'absolute inset-0 w-full h-full object-cover rounded-lg'
  end

  def quantity(book)
    unless book.available?
      return content_tag(:p, 'книга не доступна ;(')
    end

    qty = []

    if book.available_in_cit?
      qty << "Шымкент (#{book.cit_quantity})"
    end

    if book.available_in_ala?
      qty << "Алматы (#{book.ala_quantity})"
    end

    content_tag(:p, qty.join(', '))
  end

  def availability_in_cities(book)
  end

  def hide_or_show(book)
    if book.visible?
      return link_to 'Скрыть',
        book_path(@book),
        class: tw(:hide_book_btn),
        method: :delete,
        data: { confirm: 'Вы уверены, что хотите скрыть книгу?' }
    end

    link_to 'Показать',
      book_path(@book),
      class: tw(:show_book_btn),
      method: :delete,
      data: { confirm: 'Вы уверены, что хотите сделать книгу видимой?' }
  end

  def edit_link(book)
    link_to '📝',
      edit_book_path(book), 
      class: 'mx-1', 
      title: 'Редактировать'
  end

  def toggle_book_visibility(book)
    flag = book.visible? ? '🟢' : '🔴'
    flag_message = book.visible? ? 'скрыть' : 'показать'
    
    link_to flag,
      book_path(book, src: 'dashboard'),
      method: :delete,
      class: 'mx-1',
      data: {
        confirm: "Вы уверены, что хотите #{flag_message} эту книгу?"
      }
  end

end

app/views/books/_cards.html.erb
<% books.each do |book| %>
  <section class="flex p-6 my-4 bg-green-50">
      <div class="flex-none w-48 h-72 relative">
        <%= link_to cover(book), book_path(book) %>
      </div>

      <div class="flex-auto p-6">
        <h1 class="flex-auto text-xl font-bold pb-2">
          <%= link_to book.name, book_path(book), class: tw(:book_card_title) %>
        </h1>
        <div class="w-full flex-none text-sm font-medium text-gray-500 mt-2">
          <%= quantity(book) %>
        </div>
        <p class="text-base text-gray-600 my-4 font-bold">
          📗🖊️ <%= book.author %>
        </p>
        <p>
          <%= truncate book.description, length: 235, separator: ' ' %>
        </p>
      </div>
  </section>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true, class: 'flex flex-col') do |f| %>

  <% unless book.name.blank? %>
    <h1 class='text-xl font-bold mb-5'>
      <%= book.name %>
    </h1>
  <% end %>

  <%= render 'shared/errors', object: book %>

  <div class="mb-4">
    <%= f.label :name, 'Название', class: 'text-gray-600' %><br>
    <%= f.text_field :name,
                      autofocus: true, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :author, 'Автор', class: 'text-gray-600' %><br>
    <%= f.text_field :author, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>

  <div class="mb-4">
    <%= f.label :description, 'Описание', class: 'text-gray-600' %><br>
    <%= f.text_area :description, 
                    rows: 9, 
                    cols: 65,
                    class: tw(:form_text_area) %>
  </div>

  <div class="mb-4">
    <%= f.label :image_src, 'Ссылка на обложку', class: 'text-gray-600' %><br>
    <%= f.text_field :image_src, 
                      size: 33,
                      class: tw(:form_input) %>
  </div>
  
  <div class="mb-4">
    <%= f.label :ala_quantity, 'Количество (Алматы)', class: 'text-gray-600' %><br>
    <%= f.number_field :ala_quantity, 
                        min: 0, 
                        size: 33,
                        class: tw(:form_input) %>
  </div>
  
  <div class="mb-4">
    <%= f.label :cit_quantity, 'Количество (Шымкент)', class: 'text-gray-600' %><br>
    <%= f.number_field :cit_quantity, 
                        min: 0, 
                        size: 33,
                        class: tw(:form_input) %>
  </div>
  
  <div class="mb-4 checkboxes">
    <%= f.label :category_ids, 'Категории', class: 'text-gray-600' %><br>
    <%= f.collection_check_boxes :category_ids,
                        Category.all,
                        :id, :name, {},
                        class: 'checkbox' do |b| %>
      <div class="mt-1">
        <%= b.check_box %>
        <%= b.label class: 'ml-1' %>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= f.submit 'Сохранить',
                  class: 'cursor-pointer text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6' %>
  </div>

<% end %>

app/views/books/all.html.erb
<div class="text-2xl font-bold pb-2">Все книги</div>

<section class="categories flex flex-row flex-wrap">
  <%= link_to 'Все книги',
    all_books_path,
    class: tw(:category_button) %>

  <% @categories.each do |category| %>
    <%= link_to category.name,
      all_books_path(category_id: category.id),
      class: tw(:category_button) %>
  <% end %>
</section>

<%= render 'cards', books: @books %>

app/views/books/edit.html.erb
<div class="text-2xl font-bold pb-2">
  Редактировать книгу
  "<%= @book.name %>"
</div>

<section class="flex p-6 my-4 bg-green-50">
  <%= render 'form', book: @book %>
</section>

app/views/books/index.html.erb
<div class="text-2xl font-bold pb-2">Новинки</div>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to 'Добавить книгу', new_book_path, class: tw(:add_book_btn) %>
  </section>
<% end %>

<%= render 'cards', books: @books %>

app/views/books/list.html.erb
<div class="text-2xl font-bold pb-2">Все книги библиотеки</div>

<table class="flex flex-row orders-table">
  
  <tr>
    <th class="bg-blue-100 border text-left px-4 py-2">Книга</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Шымкент</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Алматы</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Прочитано</th>
    <th class="bg-blue-100 border text-left px-4 py-2 text-center">Действия</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td class="border px-4 py-2 text-sm">
        <%= link_to book.name,
                    book_path(book), 
                    class: 'text-blue-500 hover:underline' %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= book.q_cit_quantity %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= book.q_ala_quantity %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= book.times_read %>
      </td>

      <td class="border px-4 py-2 text-sm text-center">
        <%= toggle_book_visibility(book) %>
        <%= edit_link(book) %>
      </td>
    </tr>
  <% end %>

</table>

app/views/books/manage.html.erb
<div class="text-2xl font-bold pb-2">Панель управления библиотекой</div>

<section class="admin">
  <ul class="list-disc list-inside">
    <li class="mt-2">
      <%= link_to 'Добавить новую книгу 📘', new_book_path, class: 'text-blue-500 hover:underline' %>
    </li>
    <li class="mt-2">
      <%= link_to 'Добавить нового сотрудника 📘', new_user_path, class: 'text-blue-500 hover:underline' %>
    </li>
    <li class="mt-2">
      <%= link_to 'Все заказы 📥', manage_orders_path, class: 'text-blue-500 hover:underline' %>
    </li>
    <li class="mt-2">
      <%= link_to 'Все книги 📖', list_books_path, class: 'text-blue-500 hover:underline' %>
    </li>
    <li class="mt-2">
      <%= link_to 'Список читающих 🤓', manage_rentals_path, class: 'text-blue-500 hover:underline' %>
    </li>
  </ul>
  <%#= link_to 'Добавить книгу', new_book_path, class: tw(:add_book_btn) %>
</section>

app/views/books/new.html.erb
<div class="text-2xl font-bold pb-2">
  Добавить новую книгу
</div>

<section class="flex p-6 my-4 bg-green-50">
  <%= render 'form', book: @book %>
</section>

app/views/books/search.html.erb
<div class="text-2xl font-bold pb-2">
  Результаты поиска по запросу 
  "<%= @query %>"
</div>

<%= render 'cards', books: @books %>

app/views/books/show.html.erb
<div class="text-2xl font-bold pb-2">Детальная информация о книге</div>

<section class="flex p-6 my-4 bg-green-50">
  <div class="flex-none w-48 h-72 relative">
    <%= cover(@book) %>
  </div>

  <div class="flex-auto p-6">
    <h1 class="flex-auto text-2xl font-bold">
      <%= @book.name %>
    </h1>
    <p class="text-base text-gray-600 my-4 font-bold">
      📗🖊️ <%= @book.author %>
    </p>
    <p class="my-2">
      <%= @book.description %>
    </p>
    <% if @book.times_read > 0 %>
      <p class="mt-1 py-1 px-2 border-2 border-yellow-300 inline-block ">Прочитано раз: 
        <strong><%= @book.times_read %></strong>
      </p>
    <% end %>
  </div>
</section>

<section class="rental p-6 my-4 bg-green-50">
  <%= rented_out_text(@book) %>

  <%= get_from_ala(@book) %>
  <%= get_from_cit(@book) %>

  <%= readers_list(@book) %>
</section>

<% if current_user_admin? %>
  <section class="admin p-6 my-4 bg-green-50">
    <%= link_to 'Редактировать', edit_book_path(@book),  class: tw(:edit_book_btn) %>

    <%= hide_or_show(@book) %>
  </section>
<% end %>