config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  
  get 'books/all' => 'books#all', as: 'all_books'
  get 'search' => 'books#search'
  get 'admin' => 'sessions#new', as: 'admin'
  get 'return' => 'users#return', as: 'return_book'

  get 'books/manage' => 'books#manage', as: 'manage_books'
  get 'books/list' => 'books#list', as: 'list_books'
  get 'orders/manage' => 'orders#manage', as: 'manage_orders'
  get 'orders/history' => 'orders#history', as: 'order_history'
  get 'rentals/manage' => 'rentals#manage', as: 'manage_rentals'
  get 'rentals/history' => 'rentals#history', as: 'rental_history'
  put 'orders/manage/:id/moderate' => 'orders#moderate', as: 'moderate_order'
  put 'orders/manage/:id/complete' => 'orders#complete', as: 'complete_order'

  resources :books do
    resources :rentals
  end

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :orders
  resources :categories

end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="text-sm text-white text-center py-2 bg-green-500 mb-4 font-bold">
    <%= flash[:notice] %>
  </p>
<% end %>

<% if flash[:alert] %>
  <p class="text-sm text-white text-center py-2 bg-red-500 mb-4 font-bold">
    <%= flash[:alert] %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header class="border-solid border-b-2 border-yellow-600 mb-5 pb-5">
  <nav class="flex flex-row justify-between items-center">
    <div>
      <%= link_to image_tag('evrika_animated_logo.gif', class: 'w-full'), root_path %>
        <span class="<%= tw(:logo) %>">Библиотека</span>
    </div>

    <ul class="flex flex-row">
      <li class="border-r-2 border-white">
        <%= link_to 'Новинки', root_path, class: tw(:nav_item) %>
      </li>
      <li class="border-r-2 border-white">
        <%= link_to 'Все 📗', all_books_path, class: tw(:nav_item) %>
      </li>
      <li class="border-r-2 border-white">
        <%= link_to 'Заказы', orders_path, class: tw(:nav_item) %>
      </li>
      <li class="border-r-2 border-white">
        <%= link_to 'Вернуть', return_book_path, class: tw(:nav_item) %>
      </li>
    </ul>
  </nav>

  <div class="mt-5">
    <form action="/search" method="get" class="flex flex-row">
      <input
        type="text"
        name="query"
        id="search"
        placeholder="Название книги..."
        class="<%= tw(:search_input) %>">
      <input type="submit" value="Искать 👀" class="<%= tw(:search_input_submit) %>">
    </form>
  </div>

  <% if current_user %>
    <div class="admin pt-5 flex flex-row justify-end items-center">
      <%= link_to "Панель управления", manage_books_path, class: 'font-bold mx-3 border-2 border-purple-500 py-2 px-2 text-purple-500 hover:bg-purple-500 hover:border-0 hover:text-white' %>

      <div class="border-2 py-2 px-2 border-purple-500">
        <p class="font-bold text-purple-500 inline-block">
          <%= current_user.full_name %>
        </p>
        <p class="font-bold inline-block ml-2">
          <%= link_to "Выйти ➡️", session_path,
                      method: :delete, class: 'py-1 px-3 border-2 border-red-500 text-red-500 hover:border-2 hover:bg-red-500 hover:text-white' %>
        </p>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Библиотека 📚 | Evrika</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicons/favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>

    <%= stylesheet_link_tag "https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" %>
  </head>

  <body>
    <div class="max-w-3xl mx-auto px-6 py-10">

      <%= render 'layouts/header' %>

      <main class="pt-3 pb-3">
        <%= render 'layouts/flash' %>
        
        <%= yield %>
      </main>

    </div>
  </body>
</html>